### ISSUE TITLE
proc bug

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/rox-filer#4]
As mentioned [here](https://forum.puppylinux.com/viewtopic.php?p=7584) rox freezes when trying to access `/proc`.

The solution is [here](https://github.com/jun7/rox-filer/issues/214#issuecomment-653746498) so I made a patch against 17w, but i'm unsure if it affects anything else.

```patch
diff -rupN rox-filer-rox-filer-17w.orig/ROX-Filer/src/xdgmime.c rox-filer-rox-filer-17w/ROX-Filer/src/xdgmime.c
--- rox-filer-rox-filer-17w.orig/ROX-Filer/src/xdgmime.c	2019-10-15 01:54:33.000000000 +1000
+++ rox-filer-rox-filer-17w/ROX-Filer/src/xdgmime.c	2021-01-01 17:02:51.608326044 +1000
@@ -514,7 +514,10 @@ xdg_mime_get_mime_type_for_file (const c
 
       statbuf = &buf;
     }
-
+  
+  if (statbuf->st_size == 0)
+    return XDG_MIME_TYPE_EMPTY;
+    
   if (!S_ISREG (statbuf->st_mode))
     return XDG_MIME_TYPE_UNKNOWN;
 
```

Seems to work ok.

**Comment by woodenshoe-wi** [comment]
That bug gets reintroduced every time someone updates xdgmime to match the upstream version of xdgmime.

It happened back in 2012, see commit 3374e73 and then it happened again in 2019, so I fixed it in my testing branch 1b4e751 but didn’t get around to issuing any pull requests.

I do believe that is the correct fix.

**Comment by 01micko** [comment]
Thanks @woodenshoe-wi 

Seems working OK on slacko64 and 32. Raspi doesn't have the bug because it has your slightly older version.

I'll commit that patch soon.

**Comment by woodenshoe-wi** [comment]
I first noticed the problem in the 17w version as zero size files didn’t show as different icons anymore, but I thought it was just a cosmetic problem.

I didn’t know it was also causing rox to freeze, but the fix is still the same.
